services:
  - type: web
    name: liyu-bingo
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
